### ISSUE TITLE
FEAT - Add products to shopping cart

### ISSUE THREAD

**Issue by aoezalti** [aoezalti/weben-07#2]
Das Ablegen von Produkten im Warenkorb soll via AJAX erfolgen und 
ohne Page-Reload funktionieren.

Neben einem kleinen Warenkorbsymbol auf der Seite wird die aktuelle 
Anzahl der sich gerade im Warenkorb befindlichen Produkte angezeigt 
– diese Zahl wird ebenfalls via AJAX aktualisiert. Beim Stöbern durch 
die Produkte und beim „Einkaufen“ soll der User nie die Seite verlassen 
müssen.

**Comment by WI22B027** [comment]
Implementierung muss noch geprüft werden, derzeit wird das Modal nicht immer korrekt geladen und zeigt die korrekten Werte an. Beim Checkout (Button) zur Kassa muss noch die Verbindung zur Datenbank erstellt werden. Ich konnte nicht herausfinden, wie die Anbindung zur DB erfolgt.
